### ISSUE TITLE
Non `github-actions[bot]` accounts do not behave correctly

### ISSUE THREAD

**Issue by mitchellhansen-wyze** [mainmatter/continue-on-error-comment#5]
Hello again!

I have a special account that my IT org has provisioned for me for CI tasks. This account is not named `github-actions[bot]` and thus does not delete it's previous comments to the PR that it's running on.

Is it possible to do [this](https://github.com/mainmatter/continue-on-error-comment/blob/main/index.js#L23) check against the user dynamically? Or possibly adding some other metadata (magic string?) to the comment to make this user check unnecessary?

Thanks!

**Comment by mansona** [comment]
sorry it took so long to get back to you but I think my latest release should solve your issue for you.

Can you test it out and let me know if it's working 👍
